services:
  LinkageCrm\CriticalAlertingBundle\Validator\EnvValidator: ~
  LinkageCrm\CriticalAlertingBundle\Validator\ExceptionValidator: ~

  LinkageCrm\CriticalAlertingBundle\Context\RequestContext:
    arguments:
      - '@request_stack'

  LinkageCrm\CriticalAlertingBundle\EventListener\ExceptionListener:
    arguments:
      - '@LinkageCrm\CriticalAlertingBundle\Validator\EnvValidator'
      - '@LinkageCrm\CriticalAlertingBundle\Validator\ExceptionValidator'
      - '@LinkageCrm\CriticalAlertingBundle\Context\RequestContext'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }